### PR TITLE
Adding quicksilver benchmark

### PR DESCRIPTION
**Pull request by august-knox**
Initial ramble.yaml and repo files to run quicksilver on CPU, including weak and strong scaling experiments @rfhaque

### CODE REVIEW

**Review by rfhaque — APPROVED** [review]

**Comment by rfhaque** [comment]
@august-knox Good  to go. Just fix the lint formatting

**Comment by august-knox** [comment]
Hey @rfhaque, I noticed the lint error is due to a file that I hadn't changed in this PR. It seems to be coming from a file within the modifiers subfolder. Should I just fix that anyways?

**Comment by rfhaque** [comment]
> Hey @rfhaque, I noticed the lint error is due to a file that I hadn't changed in this PR. It seems to be coming from a file within the modifiers subfolder. Should I just fix that anyways?

No let it be. We can fix it in another PR.

**Comment by august-knox** [comment]
@rfhaque looks like both PRs are meeting all checks now. Should be good to go.

**Pull request merged**
