### PR TITLE
site CI: report job status, check for exit codes, add machines and benchmarks

### LINKED ISSUE #367: CI of experiments on clusters

### PR DESCRIPTION
**Pull request by slabasan**
Merge after #396. This PR extends CI support for site testing benchmarks.  Closes #367.

- [x] draft status to toggle running of gitlab
- [x] reporting pass/fail status to github
- [x] testing new workflow with saxpy on tioga
- [x] kripke (gpu) on tioga
- [x] add site user @alecbcs 
- [x] look at exit modifier in ramble

Save notes:
error message if try to init an experiment iwht a unsupported variant?
add grep here for available system+experiment variants (look for return code)
if grep CUDA; then
   append CUDA to list of variants
iterate over list of variants
   append cuda variant job to larger benchmark job
for loop over variants

### CODE REVIEW

**Comment by slabasan** [comment]
@pearce8 This one ready for merge

**Review by alecbcs — DISMISSED** [review]
@slabasan it looks like this pipeline is running too many jobs / reserving too many nodes on Tioga. We've been asked to pause or halt until we can limit the number of jobs.

**Comment by pearce8** [comment]
@slabasan heads up: #440 is likely to get merged first, at which point we need to merge latest changes from develop, and update the ci script to use the binary variants.

**Review by pearce8 — DISMISSED** [review]
SYSTEMHASH in .gitlab/ci/test.yml needs to be changed to using system_id like in .github/workflows/run.yml:

./bin/benchpark system init --dest=tioga-system llnl-elcapitan rocm=551 compiler=cce ~gtl
          ./bin/benchpark setup kripke/rocm ./tioga-system workspace/
          system_id=$(./bin/benchpark system id ./tioga-system)
          . workspace/setup.sh
          ramble \
            --workspace-dir "workspace/kripke/rocm/$system_id/workspace" \
            --disable-progress-bar \
            --disable-logger \
            workspace setup --dry-run

**Comment by slabasan** [comment]
@pearce8 Ready for merge

**Review by pearce8 — APPROVED** [review]

**Pull request merged**
