### PR TITLE
osu-microbenchmarks: rewrite as experiment.py file

### PR DESCRIPTION
**Pull request by august-knox**
Adding osu-microbenchmarks experiment.py file.

### CODE REVIEW

**Review by becker33 — COMMENTED** [review]
What is the purpose of the `programming_model` variant for this experiment?

I think the scaling nodes could also be turned into a variant, maybe @nhanford can chime in on whether that's worth doing.

Otherwise this looks good to me.

**Comment by pearce8** [comment]
Also need to add a dry-run.

**Review by pearce8 — CHANGES_REQUESTED** [review]
Need to add a dry-run.

**Review by pearce8 — APPROVED** [review]

**Review by pearce8 — CHANGES_REQUESTED** [review]
It looks like indentation errors in the dry run test prevent the worflow pipeline from executing.

**Pull request closed without merging**
