### PR TITLE
caliper top-down modifier

### PR DESCRIPTION
**Pull request by rfhaque**

### CODE REVIEW

**Comment by pearce8** [comment]
@rfhaque Can you please test on all x86 machines on-site we have defined in benchpark?

**Comment by rfhaque** [comment]
@pearce8 Tested on quartz and pascal

**Comment by slabasan** [comment]
@rfhaque Can you include here how you turn on this caliper modifier? I just have `--modifier=caliper`, but will we need more specifics to select between top-down, cuda, etc?

**Comment by pearce8** [comment]
We need to impose a constraint on the spack spec as this should only be used on Intel's x86.  If a user tries to use this modifier on a different architecture, we should make sure they get an error indicating that the modifier does not work on this architecture.  Doug provided this example: https://github.com/GoogleCloudPlatform/ramble/blob/develop/lib/ramble/ramble/language/modifier_language.py#L285

**Comment by rfhaque** [comment]
in `benchpark setup`, we specify `--modifier=caliper-topdown`

**Review by pearce8 — APPROVED** [review]

**Pull request merged**
