### PR TITLE
caliper cuda modifier

### PR DESCRIPTION
**Pull request by rfhaque**

### CODE REVIEW

**Comment by pearce8** [comment]
@rfhaque Can you please test on all cuda machines on-site we have defined in benchpark?

**Comment by rfhaque** [comment]
@pearce8 Its already tested on pascal and lassen.

**Comment by pearce8** [comment]
We need to impose a constraint on the spack spec as this should only be used on NVIDIA GPUs (where CUDA is available).  If a user tries to use this modifier on a different architecture, we should make sure they get an error indicating that the modifier does not work on this architecture.  Doug provided this example: https://github.com/GoogleCloudPlatform/ramble/blob/develop/lib/ramble/ramble/language/modifier_language.py#L285

**Comment by pearce8** [comment]
@rfhaque Also, how would one turn on this modifier?  @slabasan needs to know for the docs.

**Comment by rfhaque** [comment]
in `benchpark setup`, we specify `--modifier=caliper-cuda`

**Comment by rfhaque** [comment]
> We need to impose a constraint on the spack spec as this should only be used on NVIDIA GPUs (where CUDA is available). If a user tries to use this modifier on a different architecture, we should make sure they get an error indicating that the modifier does not work on this architecture. Doug provided this example: https://github.com/GoogleCloudPlatform/ramble/blob/develop/lib/ramble/ramble/language/modifier_language.py#L285

I'll take a look at this

**Review by pearce8 — APPROVED** [review]

**Pull request merged**
